- name: Check systemd existence as Docker Guest
  stat:
    path: /bin/systemctl
  when: ansible_virtualization_type == "docker" and ansible_virtualization_role == "guest"
  register: docker_stat_result

- name: set openvpn service name - systemd
  set_fact:
    openvpn_service_name: "openvpn@{{openvpn_config_file}}.service"
  when: ansible_service_mgr == "systemd" or (docker_stat_result is defined and docker_stat_result.stat.exists == True)

- name: disable openvpn auto-start & start
  service:
    name: "{{openvpn_service_name}}"
    enabled: no
    state: stopped

- name: Wipe out config directory
  file:
    path: "{{ openvpn_base_dir }}"
    state: absent

- name: Remove openvpn logrotate config file
  file:
    path: /etc/logrotate.d/openvpn.conf
    state: absent

- name: Uninstall OpenVPN
  package:
    name: openvpn
    state: absent

- name: Uninstall LDAP plugin
  package:
   name: openvpn-auth-ldap
   state: absent
  when: openvpn_use_ldap

- name: Terminate playbook
  fail:
    msg: "OpenVPN uninstalled, playbook stopped"
